"""add table: Record

Revision ID: 268843f9f5e8
Revises: e0514a180285
Create Date: 2018-04-14 16:31:06.709604

"""

# revision identifiers, used by Alembic.
revision = '268843f9f5e8'
down_revision = 'e0514a180285'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pn', sa.String(length=32), nullable=True),
    sa.Column('spec', sa.String(length=64), nullable=False),
    sa.Column('size', sa.String(length=64), nullable=False),
    sa.Column('customer_name', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('take_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pn')
    )
    op.create_index(op.f('ix_Records_spec'), 'Records', ['spec'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Records_spec'), table_name='Records')
    op.drop_table('Records')
    # ### end Alembic commands ###
