"""add table: Record-add username

Revision ID: 7cbd56d9d7b4
Revises: 268843f9f5e8
Create Date: 2018-04-15 12:02:38.716292

"""

# revision identifiers, used by Alembic.
revision = '7cbd56d9d7b4'
down_revision = '268843f9f5e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Records', sa.Column('username', sa.String(length=64), nullable=True))
    op.drop_index('ix_Records_spec', table_name='Records')
    op.create_index(op.f('ix_Records_spec'), 'Records', ['spec'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Records', 'username')
    op.drop_index(op.f('ix_Records_spec'), table_name='Records')
    op.create_index('ix_Records_spec', 'Records', ['spec'], unique=1)
    
    # ### end Alembic commands ###

