"""init

Revision ID: e0514a180285
Revises: 51f5ccfba190
Create Date: 2018-04-12 12:00:08.167038

"""

# revision identifiers, used by Alembic.
revision = 'e0514a180285'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pn', sa.String(length=32), nullable=True),
    sa.Column('spec', sa.String(length=64), nullable=False),
    sa.Column('size', sa.String(length=64), nullable=False),
    sa.Column('series', sa.String(length=32), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pn')
    )
    op.create_index(op.f('ix_items_spec'), 'items', ['spec'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_spec'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
