"""V1 db.Item.spec=>unique=false

Revision ID: f3e1e747d521
Revises: 
Create Date: 2018-04-18 21:49:33.855336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e1e747d521'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index('ix_Records_spec', table_name='Records')
    op.drop_index('ix_items_spec', table_name='items')
    op.create_index(op.f('ix_items_spec'), 'items', ['spec'], unique=False)
    op.create_index(op.f('ix_Records_spec'), 'Records', ['spec'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Records_spec'), table_name='Records')
    op.drop_index(op.f('ix_items_spec'), table_name='items')
    op.create_index('ix_items_spec', 'items', ['spec'], unique=1)
    op.create_index('ix_Records_spec', 'Records', ['spec'], unique=False)
    # ### end Alembic commands ###
